services:
  weatherapp:
    image: weatherapp
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://+:80
      - OpenWeatherMapApiKey=4fd090bd393cbeff3c8a7eba16a02cc8
      # You can set your API key here
      # - OpenWeatherMapApiKey=YOUR_API_KEY_HERE 